$(document).ready(function(){
    $("#img").click(function(){
        $("#p").show();
        $("#img").hide();
    });
    $("#p").click(function(){
        $("#img").show();
        $("#p").hide();
    });
    $("#img1").click(function(){
        $("#p1").show();
        $("#img1").hide();
     });
     $("#p1").click(function(){
         $("#img1").show();
         $("#p1").hide();
     });
     $("#img2").click(function(){
         $("#p2").show();
         $("#img2").hide();
     });
     $("#p2").click(function(){
         $("#img2").show();
         $("#p2").hide();
     });
     
});